export default function Favorites() {
    return (
        <>
            <h2>These are a few of my favorite things</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui faucibus in ornare quam viverra orci sagittis eu. Tincidunt praesent semper feugiat nibh sed pulvinar. Est lorem ipsum dolor sit amet consectetur. A scelerisque purus semper eget duis. Semper quis lectus nulla at. Feugiat nibh sed pulvinar proin gravida hendrerit. Placerat in egestas erat imperdiet sed euismod nisi porta. Sapien nec sagittis aliquam malesuada bibendum. Erat nam at lectus urna duis. Vitae congue mauris rhoncus aenean vel elit scelerisque.

At imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Dolor sit amet consectetur adipiscing elit. Sed libero enim sed faucibus turpis in eu mi bibendum. Sem integer vitae justo eget magna. Porttitor rhoncus dolor purus non enim. Sed faucibus turpis in eu mi bibendum neque egestas congue. Placerat in egestas erat imperdiet sed. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Orci a scelerisque purus semper eget. Mauris sit amet massa vitae. Neque egestas congue quisque egestas. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Vitae turpis massa sed elementum tempus. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Tortor condimentum lacinia quis vel eros. Proin nibh nisl condimentum id venenatis a condimentum vitae sapien. Elit duis tristique sollicitudin nibh sit. Sem nulla pharetra diam sit amet nisl suscipit adipiscing. Justo nec ultrices dui sapien eget mi. Elementum integer enim neque volutpat ac.

Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor. Tortor aliquam nulla facilisi cras fermentum. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Lacinia quis vel eros donec ac odio. Lectus nulla at volutpat diam ut venenatis. Volutpat lacus laoreet non curabitur. Sed blandit libero volutpat sed. Id semper risus in hendrerit. Scelerisque felis imperdiet proin fermentum.

Aliquam etiam erat velit scelerisque. Turpis egestas pretium aenean pharetra. Bibendum at varius vel pharetra vel turpis. Nulla malesuada pellentesque elit eget gravida cum sociis. Magna sit amet purus gravida. Morbi tristique senectus et netus et malesuada fames. Volutpat lacus laoreet non curabitur gravida. Amet tellus cras adipiscing enim eu turpis egestas pretium aenean. Donec ultrices tincidunt arcu non sodales neque. Eu sem integer vitae justo eget magna. Donec massa sapien faucibus et molestie. Dui id ornare arcu odio ut. Tellus cras adipiscing enim eu turpis egestas pretium aenean.

Est placerat in egestas erat imperdiet sed euismod nisi porta. Varius sit amet mattis vulputate enim nulla aliquet porttitor. Euismod nisi porta lorem mollis aliquam ut porttitor leo a. Tortor consequat id porta nibh venenatis cras. Fusce id velit ut tortor pretium viverra. Tortor at auctor urna nunc id cursus. Neque sodales ut etiam sit amet nisl purus in mollis. Tincidunt praesent semper feugiat nibh sed pulvinar. Id porta nibh venenatis cras sed felis eget velit. Amet dictum sit amet justo donec. Tellus cras adipiscing enim eu turpis. Amet dictum sit amet justo. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Vulputate dignissim suspendisse in est ante in.</p>
        </>
    )
}